// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX_HjFwXDwt3yW8oiyvVySPJeRJVO1Zaw',
    appId: '1:797834892606:android:da00610b817cc5f5fdc86f',
    messagingSenderId: '797834892606',
    projectId: 'dbmagang-ec5dc',
    storageBucket: 'dbmagang-ec5dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArPeGdDQ2GgbQFXmguZiOX9w-rRTHQlhc',
    appId: '1:828810399391:ios:2f6569c75ddee831739caa',
    messagingSenderId: '828810399391',
    projectId: 'maroonapp-81251',
    storageBucket: 'maroonapp-81251.appspot.com',
    iosBundleId: 'com.example.maroonApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByEHEhfsy95rGaAqwpNqy1u9g4OJssnKg',
    appId: '1:828810399391:web:4160221c30853c85739caa',
    messagingSenderId: '828810399391',
    projectId: 'maroonapp-81251',
    authDomain: 'maroonapp-81251.firebaseapp.com',
    storageBucket: 'maroonapp-81251.appspot.com',
  );
}